# Site settings
title: Andre Richter
email: andre.richter@sofi.su.se
description: I'm a PhD Candidate at the Swedish Institute for Social Research. 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://a-richter.github.io"
github_username:  a-richter
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
markdown: kramdown
theme: minima
disqus:
  shortname: a-richter

# needed for CI builds:
exclude: [vendor]
