title: Andre Richter
url: "http://a-richter.github.io"
baseurl: "/" 
github_username:  a-richter
permalink: /blog/:year/:month/:title.html

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
